---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	collect_info(collect_info)
	verify_patient(verify_patient)
	agent(agent)
	tools(tools)
	process_results(process_results)
	__end__([<p>__end__</p>]):::last
	__start__ --> agent;
	agent -. &nbsp;end&nbsp; .-> __end__;
	agent -.-> collect_info;
	agent -.-> tools;
	agent -.-> verify_patient;
	collect_info --> agent;
	process_results --> agent;
	tools --> process_results;
	verify_patient --> agent;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
